services:
  mysql:
    image: mysql:8.0
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: rootpass
      MYSQL_DATABASE: barberia_alura
    ports:
      - "3306:3306"
    volumes:
      - mysql_data:/var/lib/mysql

  backend:
    build: .
    depends_on:
      - mysql
    environment:
      DB_HOST: mysql
      DB_USER: root
      DB_PASSWORD: rootpass
      DB_NAME: barberia_alura
      PORT: 3000
    ports:
      - "3000:3000"
    volumes:
      - .:/app
    command: sh -c "sleep 20 && node index.js" # Espera a que MySQL arranque

volumes:
  mysql_data:
